display_name: lizaplayer
package_name: lizaplayer

maintainer:
  name: lizapropanol
  email: noreply@example.com

priority: optional

section: sound

installed_size: 55233357

dependencies:
  - libgtk-3-0
  - libsecret-1-0
  - liblzma5
  - libglib2.0-0
  - libayatana-appindicator3-1
  - libmpv1 | libmpv2

essential: false

icon: linux/assets/icon.png

keywords:
  - Music
  - Player
  - Yandex
  - SoundCloud

generic_name: Music Player

categories:
  - Audio
  - Music

startup_notify: true

description: |-
  Custom Yandex Music/SoundCloud player.
  A Flutter-based desktop app for streaming and playing music from Yandex and SC.
